-- ifs_opt_controller_common.lua
-- Decompiled with SWBF2CodeHelper
Platform_btn_map = {
    {
        name = "bstr",
        type = 1,
        x = 14.800000190735,
        y = -3.2000000476837,
        hiTex = "",
        w = 11,
        h = 11,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = -220,
        ly1 = -35,
        lx2 = 0,
        ly2 = 0
    },
    {
        name = "bsel",
        type = 1,
        x = -27,
        y = -3.2000000476837,
        hiTex = "",
        w = 11,
        h = 11,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = -220,
        ly1 = 0,
        lx2 = 0,
        ly2 = -5
    },
    {
        name = "dpadl",
        type = 1,
        x = -90,
        y = -2,
        hiTex = "",
        w = 14,
        h = 14,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = -40,
        ly1 = -65,
        lx2 = 0,
        ly2 = 5
    },
    {
        name = "dpadr",
        type = 1,
        x = -65,
        y = -2,
        hiTex = "",
        w = 14,
        h = 14,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = -40,
        ly1 = -20,
        lx2 = 0,
        ly2 = -5
    },
    {
        name = "dpadu",
        type = 1,
        x = -78.5,
        y = -15.5,
        hiTex = "",
        w = 16,
        h = 16,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = -40,
        ly1 = 15,
        lx2 = 0,
        ly2 = -35
    },
    {
        name = "dpadd",
        type = 1,
        x = -78.5,
        y = 11.5,
        hiTex = "",
        w = 16,
        h = 16,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = -40,
        ly1 = 50,
        lx2 = 0,
        ly2 = -15
    },
    {
        name = "lang",
        type = 3,
        x = -46,
        y = 24,
        hiTex = "",
        w = 38,
        h = 38,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = -220,
        ly1 = 40,
        lx2 = 0,
        ly2 = 45
    },
    {
        name = "bsqr",
        type = 1,
        x = 32,
        y = -4,
        hiTex = "",
        w = 16,
        h = 16,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = 100,
        ly1 = -20,
        lx2 = 0,
        ly2 = -7
    },
    {
        name = "bcir",
        type = 1,
        x = 60,
        y = -4,
        hiTex = "",
        w = 16,
        h = 16,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = 100,
        ly1 = 50,
        lx2 = 0,
        ly2 = 4
    },
    {
        name = "btri",
        type = 1,
        x = 46,
        y = -20,
        hiTex = "",
        w = 16,
        h = 16,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = 100,
        ly1 = -65,
        lx2 = 0,
        ly2 = -15
    },
    {
        name = "bcrs",
        type = 1,
        x = 46,
        y = 14,
        hiTex = "",
        w = 16,
        h = 16,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = 100,
        ly1 = 15,
        lx2 = 0,
        ly2 = 24
    },
    {
        name = "ltrig1",
        type = 1,
        x = -74,
        y = -75,
        hiTex = "",
        w = 32,
        h = 32,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = -40,
        ly1 = -100,
        lx2 = 0,
        ly2 = -58
    },
    {
        name = "rtrig1",
        type = 1,
        x = 39.5,
        y = -75,
        hiTex = "",
        w = 32,
        h = 32,
        conL = 0,
        conR = 0,
        conU = 0,
        conD = 0,
        func = 2,
        lx1 = 100,
        ly1 = -100,
        lx2 = 0,
        ly2 = -58
    },
    {
        name = "yflip",
        type = 5,
        x = 45,
        y = 435,
        hiTex = "",
        w = 20,
        h = 20,
        conL = 0,
        conR = 0,
        conU = 15,
        conD = 15,
        func = 2,
        lx1 = -220,
        ly1 = 202,
        lx2 = 0,
        ly2 = 202
    },
    {
        name = "reset",
        type = 5,
        x = 0,
        y = 205,
        hiTex = "",
        w = 0,
        h = 0,
        conL = 0,
        conR = 0,
        conU = 14,
        conD = 14,
        func = 2,
        lx1 = -220,
        ly1 = 202,
        lx2 = 0,
        ly2 = 202
    }
}
Preset_btn_index = 15
